before_install:
  - sudo add-apt-repository "deb http://apt.wikimedia.org/wikimedia precise-wikimedia main universe"
  - sudo apt-get update

install:
  - sudo apt-get install -y --force-yes gdnsd

before_script:
  - sudo cp config /etc/gdnsd/
  - sudo cp zones/orain.org /etc/gdnsd/zones/

script:
  - sudo gdnsd checkconf

notifications:
  irc:
    channels:
      - "chat.freenode.net#orain"
    on_success: change
    on_failure: always
    skip_join: true
    template:
      - "%{repository}/%{branch}/%{commit} - %{author} 
%{message} %{build_url}"
  email:
    recipients:
      - john@orain.org
    on_success: change
    on_failure: always
